// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "ITerminalConnection.idl";

namespace Microsoft.Terminal.TerminalConnection
{
    [default_interface] runtimeclass SerialConnection : ITerminalConnection
    {
        static Guid ConnectionType { get; };

        SerialConnection();

        String PortName { get; };
        void SwitchPort(String portName);

        static Windows.Foundation.Collections.ValueSet CreateSettings(String commandline,
                                                                      UInt32 rows,
                                                                      UInt32 columns,
                                                                      Guid guid,
                                                                      Guid profileGuid);
    };
}
